config/routes.rb
Oinkbay::Application.routes.draw do
  get "users/show"

  resources :pins

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  match 'users/:id' => 'users#show', as: :user
  match 'like/:id' => 'pins#vote_up', :as => 'like'
  match 'notlike/:id' => 'pins#vote_down', :as => 'notlike'
  
  root :to => 'pages#home'
  get 'gallery' => 'pins#index'
  get 'mypage' => 'users#mypage'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :image_remote_url

  validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
  								content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
  								size: { less_than: 5.megabytes }

  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>" }

  make_voteable
  def image_remote_url=(url_value)
  	self.image = URI.parse(url_value) unless url_value.blank?
  	super
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
         :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :firstname, :lastname, :username, :email, :password, :password_confirmation, :remember_me, :provider, :uid
  # attr_accessible :title, :body

  has_many :pins, dependent: :destroy

  validates_presence_of :username
  validates_uniqueness_of :username

  make_voter
	def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
		user = User.where(:provider => auth.provider, :uid => auth.uid).first
		unless user
			user = User.create(username:auth.extra.raw_info.username,
			firstname: auth.extra.raw_info.first_name,
			lastname: auth.extra.raw_info.last_name,
			provider:auth.provider,
			uid:auth.uid,
			email:auth.info.email,
			password:Devise.friendly_token[0,20])
		end
		user
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def market
  end

  def mypage
  end



end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  #Authenticate user, must be logged in to create/ edit pins. 
  #except: allows user to see list but not change
  before_filter :authenticate_user!, except: [:index]
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
  
  def vote_up
	@pin = Pin.find(params[:id])
	current_user.up_vote!(@pin)
	respond_to do |format|
		format.js
	end
  end
  
  def vote_down
	@pin = Pin.find(params[:id])
	current_user.down_vote!(@pin)
	respond_to do |format|
		format.js
	end
	#redirect_to @pin, notice: 'Thanks for Voting'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
		# You need to implement the method below in your model (e.g. app/models/user.rb)
		@user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

		if @user.persisted?
			sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
			set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@pins = @user.pins.page(params[:page]).per_page(20)
  end


 def mypage
  	@user = current_user
  	@pins = @user.pins.page(params[:page]).per_page(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
<br>
  	<p class="pull-right">
  		<%= link_to "Back to top","#" %>
  	</p>
        
    <p>© 2013 OinkBay · <%= link_to "Privacy", "#" %> · <%= link_to "Terms", "#" %></p>
</div>

app/views/layouts/_header.html.erb
<!-- NAVBAR
    ================================================== -->
    <div class="navbar-wrapper">
      <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
      <div class="container">

        <div class="navbar navbar-fixed-top">
          <div class="navbar-inner">
            <!-- navbar-inverse before navbarfixedtop Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to(image_tag("somepiglogo.png", :class => "brand"), root_path) %>
            <div class="nav-collapse collapse">
              
              <ul class="nav">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "About", about_path %></li>
				<li><%= link_to "Gallery", gallery_path %></li>
              </ul>
                <ul class="nav pull-right">    
                  <% if user_signed_in? %>
                    <li><p class="nav navbar-text"><small>Hi <%= link_to current_user.firstname, edit_user_registration_path %>!</small></li>
                    <li><%= link_to "My Page", mypage_path %></li>
                    <li><%= link_to "Add +", new_pin_path %></li>
                    <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li></p>
                  <% else %>     
                    <li><%= link_to "Sign Up", new_user_registration_path %></li>
                    <li><%= link_to "Login", new_user_session_path %></li>
					 <li><%= link_to image_tag("facebook_login.png"), user_omniauth_authorize_path(:facebook) %></li>
                  <% end %>
                </ul>

            </div><!--/.nav-collapse -->
          </div><!-- /.navbar-inner -->
        </div><!-- /.navbar -->

      </div> <!-- /.container -->
    </div><!-- /.navbar-wrapper -->



app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SOME PIG!</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
  
</html>

app/views/pages/about.html.erb
<br>
<h1>About</h1>
<br>

<p>
<h4><strong>What is Some Pig?</strong></h4>
Some Pig is a place for people to share, comment on and vote for pig pictures. We are also working to add discussion forums and other pig-related features.
</p><br>

<p>
<h4><strong>Why Some Pig? </strong></h4>
Pigs rock. They are maddeningly cute and wickedly clever. Everyone loves pigs.
</p><br>

<p>
<h4><strong>What does Some Pig mean?</strong></h4>
If you have to ask this, you obviously weren't fully read-up on your literature as a child. Go to the bookstore and pick up <i>Charlotte's Web</i>.
</p><br>

<p>
<h4><strong>Who is Some Pig?</strong></h4>
Some Pig was created by two people who couldn't be more different from each other. But, we do like pigs. We don't have piggy pets, but if we could, we would. We both live in cities and homes that wouldn't cater well to little snortly friends, and this is unfortunate.
</p>
<br>

<%= image_tag("woofberryteam.png") %> <br>
<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; THE KINGPIG &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PRIME PIG</strong><br><br><br>

app/views/pages/contact.html.erb
<br>
<h1>Contact Page</h1>

app/views/pages/home.html.erb
<!DOCTYPE html>

<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">

    <meta name="description" content="">
    <meta name="author" content="">

     <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing"><br><br><br><br><br><br><br>

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="span4">
          <%= image_tag("Pig3b.png", :class => "img-circle", :size => "180x180") %>
          <h2>Pig View</h2>
          <p>Want to see some awesome pigs? You've come to the right place. Our gallery is full of pictures of really, really, REALLY spectacular pigs. </p><br>
			<p><%= link_to "Some Pig", gallery_path, class: "btn btn-large btn-custom" %></p>
        </div><!-- /.span4 -->
        <div class="span4">
          <%= image_tag("Pigb.png", :class => "img-circle", :size => "180x180") %>
          <h2>Add Pig</h2>
          <p>Have an adorable pig? Upload its picture here. Go ahead, I'm sure it'll pay you generously in snortles and oinks. And bacon. </p><br>
          <p>
			<% if user_signed_in? %>
				<%= link_to "Terrific»", new_pin_path, class: "btn btn-large btn-custom" %>
			<% else %>
				<%= link_to "Terrific»", new_user_registration_path, class: "btn btn-large btn-custom" %>
			<% end %>
		  </p>
        </div><!-- /.span4 -->
        <div class="span4">
          <%= image_tag("Pig2b.png", :class => "img-circle", :size => "180x180") %>
          <h2>Pig It Up</h2>
          <p>Show your love for your favorite pigs by pigging them up. Go ahead, we've already made a nice little button for you.</p><br>
          <p>
			<% if user_signed_in? %>
				<%= link_to "Radiant»", new_pin_path, class: "btn btn-large btn-custom" %>
			<% else %>
				<%= link_to "Radiant»", new_user_registration_path, class: "btn btn-large btn-custom" %>
			<% end %>
		  </p>
        </div><!-- /.span4 -->
      </div><!-- /.row --><br><br><br>


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="featurette">
        <%= image_tag("bigpig1.png", :class => "featurette-image pull-right", :size => "400x400") %>
        <h2 class="featurette-heading">Bigwig Bigpig 
        <span class="muted">Look at some pigs</span></h2>
        <p class="lead"> Want to see pictures of awesome pigs? You've come to the right place. We welcome all kinds of pigs here, we're an equal opportunity pig gallery. It's been proven by the Fictional Pig College of Social Sciences that looking at pictures of pigs is cathartic. So if you need a pick-me-up at work, look no further.</p>
      </div>

      <hr class="featurette-divider">

      <div class="featurette">
        <%= image_tag("bigpig3.png", :class => "featurette-image pull-left", :size => "400x400") %>
        <h2 class="featurette-heading">Share Some Pig.
       <span class="muted">You got a gig.</span></h2>
        <p class="lead">If you have pictures of awesome pigs, put them up. We are the United Nations, or if you are the shopping sort, the Benetton of Pigs. Big, small, pink, brown, or just oinking fantastic, your picture belongs here. And if you're super awesome, piglovers everywhere will vote you up and you'll be SOME PIG!</p>
      </div>

      <hr class="featurette-divider">

      <div class="featurette">
        <%= image_tag("bigpig2.png", :class => "featurette-image pull-right", :size => "400x400") %>
        <h2 class="featurette-heading">Pigtastic. <span class="muted">Up-pig the best pic.</span></h2>
        <p class="lead">If you like what you see, you need to vote that picture up. We've made it really easy too, by providing you with a neat little SOME PIG button. All you have to do is lick on it and say 'Oink', and your vote will be counted. The piggies with the most votes enjoy all kinds of privileges, such as piggy fame and prominence in the piggy tabloids. </p>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->

      <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="./home_files/jquery.js"></script>
    <script src="./home_files/bootstrap-transition.js"></script>
    <script src="./home_files/bootstrap-alert.js"></script>
    <script src="./home_files/bootstrap-modal.js"></script>
    <script src="./home_files/bootstrap-dropdown.js"></script>
    <script src="./home_files/bootstrap-scrollspy.js"></script>
    <script src="./home_files/bootstrap-tab.js"></script>
    <script src="./home_files/bootstrap-tooltip.js"></script>
    <script src="./home_files/bootstrap-popover.js"></script>
    <script src="./home_files/bootstrap-button.js"></script>
    <script src="./home_files/bootstrap-collapse.js"></script>
    <script src="./home_files/bootstrap-carousel.js"></script>
    <script src="./home_files/bootstrap-typeahead.js"></script>
    <script>
      !function ($) {
        $(function(){
          // carousel demo
          $('#myCarousel').carousel()
        })
      }(window.jQuery)
    </script>
    <script src="./home_files/holder.js"></script>
  

app/views/pins/_dislike.html.erb
<%= @pin.down_votes %>

app/views/pins/_form.html.erb
<br>
<%= simple_form_for(@pin, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload an image" %>
  <%= f.input :image_remote_url, label: "or enter image URL" %>

    <%= f.input :description, as: :text, input_html: { rows: "3"} %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_like.html.erb
<%= @pin.up_votes %>

app/views/pins/_likeform.html.erb
<%= form_tag(like_path(@pin.id), :remote => true, :style => 'display: inline;') do %>
	<%= image_submit_tag("like.png", :alt => "Like!", :title => "Like!") %>
	<div id="likes" style="display: inline;">
		<%= render :partial => "like" %>
	</div>
<% end %>
<%= form_tag(notlike_path(@pin.id), :remote => true, :style => 'display: inline;') do %>
	<%= image_submit_tag("dislike.png", :alt => "Dislike!", :title => "Dislike!", :style => 'display: inline;') %>
	<div id="dislikes" style="display: inline;">
		<%= render :partial => "dislike" %>
	</div>
<% end %>

app/views/pins/_pin.html.erb
<br>
<div class="box">
	<%= link_to (image_tag pin.image(:medium)), pin %>
	<p class="description">
		<span style="margin-left:1px; background-color:rgba(0, 0, 0, 0.3); -webkit-appearance:none;">
			<font color="white">&nbsp;<%= pin.description %>&nbsp;</font></span>
	</p>

	<span style="margin-left:8px; background-color:rgba(0, 0, 0, 0.3); -webkit-appearance:none;">
		<font color="white">
			&nbsp;by <strong><u><%= link_to pin.user.username, pin.user, {:style => 'color: #FFFFFF'} %></u></strong>&nbsp;
		</font>
	</span>


	  <% if current_user == pin.user %>
	    <br><br><p>
	      <%= link_to 'Edit', edit_pin_path(pin) %>
	      <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
	    </p>
	  <% end %>
</div>

app/views/pins/edit.html.erb
<br>
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<br><br>

<div id="pins">
	<%= render @pins %>
</div>

<%= will_paginate @pins %>

app/views/pins/index.js.erb
<br>
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
  $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/pins/mypage.html.erb
<h1><%= @user.firstname %> <%= @user.lastname %></h1>

<div id="pins">
	<%= render @pins %>
</div>

<%= will_paginate @pins %>


app/views/pins/new.html.erb
<br>
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<br>
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @pin.image %>
			<p>
			  <br><%= @pin.description %>
			</p>
			<p>
			 by <%= @pin.user.username %>
			</p>
			<div  id="likeform">
				<%= render :partial => "likeform" %>
			</div>

			<% if current_user == @pin.user %>
				<%= link_to 'Edit', edit_pin_path(@pin) %> |
			<% end %>
				<%= link_to 'Back', pins_path %>
		</div>
	</div>
</div>

app/views/pins/vote_down.js.erb
$('#dislikes').html("<%= escape_javascript(render(:partial => 'pins/dislike')).html_safe %>");
$('#likes').html("<%= escape_javascript(render(:partial => 'pins/like')).html_safe %>");

app/views/pins/vote_up.js.erb
$('#dislikes').html("<%= escape_javascript(render(:partial => 'pins/dislike')).html_safe %>");
$('#likes').html("<%= escape_javascript(render(:partial => 'pins/like')).html_safe %>");

app/views/users/mypage.html.erb
<br>
<h1><%= current_user.firstname %> <%= current_user.lastname %></h1>

<div id="pins">
	<%= render @pins %>
</div>

<%= will_paginate @pins %>

app/views/users/show.html.erb
<br>
<h1><%= @user.firstname %> <%= @user.lastname %></h1>

<div id="pins">
	<%= render @pins %>
</div>

<%= will_paginate @pins %>